services:
  db:
    image: postgres:16
    container_name: musicbox-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/Tristanchz2/musicweb-backend:latest
    container_name: musicbox-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      MUSIC_STORAGE_PATH: /data/music
    ports:
      - "8000:8000"
    volumes:
      - music_data:/data/music

volumes:
  postgres_data:
  music_data: